name: Build

on:
  push:
    # branches:
      # - master
  pull_request:

jobs:
  build:
    name: Test ${{ matrix.luaVersion }} on ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        luaVersion: [ "luajit", "luajit-openresty" ]
        platform: [ "windows-2022" ]
        # luaVersion: [ "5.4", "5.3", "5.2", "5.1", "luajit", "luajit-openresty" ]
        # platform: [ "ubuntu-22.04", "macos-14", "windows-2022" ]
    runs-on: ${{ matrix.platform }}
    steps:
      # - name: Use the MinGW C compiler shipped with Strawberry Perl
      #   if: ${{ runner.os == 'Windows' }}
      #   run: |
      #     C:\msys64\usr\bin\bash -lc "pacman -S mingw-w64-ucrt-x86_64-cc mingw-w64-ucrt-x86_64-make --noconfirm"
      #     Add-Content "${{ github.path }}" "C:\msys64\ucrt64\bin"

      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup ’msvc’
        if: ${{ startsWith(matrix.platform, 'windows') && !startsWith(matrix.luaVersion, 'luajit') }}
        uses: ilammy/msvc-dev-cmd@v1
      - name: Setup ‘lua’
        uses: luarocks/gh-actions-lua@v10
        with:
          luaVersion: ${{ matrix.luaVersion }}
      - name: Setup ‘luarocks’
        uses: luarocks/gh-actions-luarocks@v5

      - name: "Config LuaRocks"
        if: ${{ runner.os == 'Windows' && startsWith(matrix.luaVersion, 'luajit') }}
        run: luarocks config lua_dir "${{ github.workspace }}\.lua"
      
      - name: Make and install
        run: |
          luarocks make -- luasocket-scm-3.rockspec
        env:
          DEBUG: DEBUG
      # - name: Make and install
      #   run: |
      #     luarocks install luasocket
      - name: Run regression tests
        shell: bash
        run: |
          cd test
          lua hello.lua
          lua testsrvr.lua > /dev/null &
          lua testclnt.lua
          lua stufftest.lua
          lua excepttest.lua
          lua test_bind.lua
          lua test_getaddrinfo.lua
          lua ltn12test.lua
          lua mimetest.lua
          lua urltest.lua
          lua test_socket_error.lua
          kill %1
